site_name: Ansible lab
repo_url: https://github.com/dunossauro/ansible-lab
repo_name: dunossauro/ansible-lab
docs_dir: docs
edit_uri: tree/main/docs

theme:
  name: material
  language: pt
  logo: images/ansible_logo.png
  favicon: images/ansible_logo.png
  features:
    - content.tabs.link
  icon:
    repo: fontawesome/brands/git-alt

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - admonition
  - markdown.extensions.attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dunossauro
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dunossauro
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/dunossauro
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/dunossauro
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@dunossauro

plugins:
  - mkdocs-video
