---
- name: Configuração do ambiente python
  hosts: linux

  tasks:
    - name: install pyenv (Arch)
      become: yes
      package:
        state: present
        name: pyenv
      when: ansible_distribution == 'Archlinux'

    - name: Clone Pyenv (Ubuntu)
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: ~/.pyenv
      when: ansible_distribution == 'Ubuntu'

    - name: config pyenv
      blockinfile:
        dest: ~/.bashrc
        block: |
          echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init -)"' >>~/.bashrc
          echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
          echo 'PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc

    - name: Show bashrc
      shell: cat ~/.bashrc
      register: bashrc

    - name: Checking bashrc
      debug:
        msg: "{{ bashrc.stdout.split('\n') }}"

    - block:
        - name: install python3.11
          shell: pyenv install -s 3.11:latest
          register: pyenv_result
      rescue:
        - name: Debug pyenv fail
          debug:
            msg: "{{pyenv_result.stderr.split('\n') }}"
          when: pyenv_result.failed

