---
- name: Configuração do app python
  hosts: test
  become: yes

  tasks:
    - name: install build tools
      package:
        name: base-devel
        state: present

    - name: install pyenv
      package:
        state: present
        name: pyenv

    - name: install python3.10
      shell: pyenv install 3.10:latest

    - name: install python3.11
      shell: pyenv install 3.11:latest

    - name: set 3.11 global
      shell: pyenv global 3.11:latest

    - name: Install pipx
      shell: echo python --version && pip install pipx
