---
- name: Configura o ambiente de desenvolvimento
  hosts: linux
  gather_facts: true


  tasks:
    - name: Dependências de desenvolvimento
      become: true
      import_tasks: tasks/dev_env.yml

    - name: Pyenv install
      import_tasks: tasks/pyenv.yml

    - name: Install python 3.11
      import_tasks: tasks/py_311.yml
