---
- name: Configura o ambiente de desenvolvimento
  hosts: linux
  gather_facts: true


  tasks:
    - name: Dependências de desenvolvimento
      become: true
      import_tasks: tasks/dev_env.yml

  roles:
    - role: staticdev.pyenv
      pyenv_env: user
      pyenv_global:
        - 3.11.0
      pyenv_python_versions:
        - 3.11.0
